import 'dart:io';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  static Future<void> exportShoppingList(
    BuildContext context,
    Map<String, List<String>> grouped,
  ) async {
    final pdf = pw.Document();
    final dateStr = DateFormat('MMMM d, yyyy').format(DateTime.now());

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'My Shopping List',
              style: pw.TextStyle(
                fontSize: 28,
                fontWeight: pw.FontWeight.bold,
                color: PdfColor.fromHex('#E07B39'),
              ),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              dateStr,
              style: const pw.TextStyle(
                fontSize: 12,
                color: PdfColors.grey600,
              ),
            ),
            pw.Divider(color: PdfColor.fromHex('#E07B39'), thickness: 1.5),
            pw.SizedBox(height: 8),
          ],
        ),
        build: (ctx) {
          final List<pw.Widget> widgets = [];

          grouped.forEach((recipeName, ingredients) {
            widgets.add(
              pw.Container(
                margin: const pw.EdgeInsets.only(top: 16, bottom: 8),
                padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('#FFF3EB'),
                  borderRadius: pw.BorderRadius.circular(6),
                ),
                child: pw.Text(
                  recipeName,
                  style: pw.TextStyle(
                    fontSize: 14,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromHex('#C0622A'),
                  ),
                ),
              ),
            );

            for (final ingredient in ingredients) {
              widgets.add(
                pw.Padding(
                  padding: const pw.EdgeInsets.symmetric(vertical: 3, horizontal: 4),
                  child: pw.Row(
                    children: [
                      pw.Container(
                        width: 6,
                        height: 6,
                        margin: const pw.EdgeInsets.only(right: 10, top: 3),
                        decoration: pw.BoxDecoration(
                          color: PdfColor.fromHex('#E07B39'),
                          shape: pw.BoxShape.circle,
                        ),
                      ),
                      pw.Expanded(
                        child: pw.Text(
                          ingredient,
                          style: const pw.TextStyle(fontSize: 12),
                        ),
                      ),
                    ],
                  ),
                ),
              );
            }
          });

          return widgets;
        },
        footer: (ctx) => pw.Center(
          child: pw.Text(
            'Generated by Recipe App • ${ctx.pageNumber} of ${ctx.pagesCount}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
          ),
        ),
      ),
    );

    // Save to temp file and share
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/shopping_list_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await pdf.save());

    // Show PDF viewer with share option
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Shopping List',
    );
  }
}
